--- 
clone: 
  depth: 1
kind: pipeline
name : OldCam
version: Nexus-OLD
steps:
 - name: Nexus
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh --old

---
clone:
  depth: 1
kind: pipeline
name : NewCam
version: Nexus-NEW
steps:
 - name: Nexus
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh --new

---
clone:
  depth: 1
kind: pipeline
name : Qti-Old
version: Nexus-QTI-OLD
steps:
 - name: Nexus
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - git apply QTI_HAPTICS.p
     - /noclone3 bash build.sh --qti

---
clone:
  depth: 1
kind: pipeline
name : A12-Qti-Old
version: Nexus-A12-QTI-OLD
steps: 
 - name: Nexus
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - git apply QTI_HAPTICS.p
     - git apply a12.p
     - /noclone3 bash build.sh --a12-qti
